-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 00:00:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ashure_DR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ashure_DR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ashure_DR` DEFAULT CHARACTER SET utf8 ;
USE `Ashure_DR` ;

-- -----------------------------------------------------
-- Table `Ashure_DR`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  `Apellido_paterno` VARCHAR(20) NULL,
  `Apellido_materno` VARCHAR(50) NULL,
  `Telefono` VARCHAR(10) NULL,
  `Correo` VARCHAR(50) NULL,
  `Contraseña` VARCHAR(50) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  `Apellido_paterno` VARCHAR(20) NULL,
  `Apellido_materno` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Genero` VARCHAR(10) NULL,
  `Calle` VARCHAR(100) NULL,
  `Ciudad` VARCHAR(50) NULL,
  `Estado` VARCHAR(20) NULL,
  `CP` INT NULL,
  `Correo` VARCHAR(50) NULL,
  `Fecha_contratacion` DATE NULL,
  `Cargo` VARCHAR(20) NULL,
  `Salario` INT NULL,
  `Activo` VARCHAR(10) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Usuario_idUsuario`),
  INDEX `fk_Empleado_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Ashure_DR`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Turno_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Turno_horario` (
  `Turno_horario` INT NOT NULL,
  `Nombre_turno` VARCHAR(20) NULL,
  `Hora_inicio` VARCHAR(20) NULL,
  `Hora_finalizacion` VARCHAR(20) NULL,
  `Dias_semana` VARCHAR(20) NULL,
  `Fecha_inicio` DATE NULL,
  `Fecha_finalizacion` DATE NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`Turno_horario`, `Empleado_idEmpleado`),
  INDEX `fk_Turno_horario_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Turno_horario_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Asistencia` (
  `idAsistencia` INT NOT NULL,
  `Fecha_hora_entrada` DATETIME NULL,
  `Fecha_hora_salida` DATETIME NULL,
  `Turno_horario_Turno_horario` INT NOT NULL,
  `Turno_horario_Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idAsistencia`, `Turno_horario_Turno_horario`, `Turno_horario_Empleado_idEmpleado`),
  INDEX `fk_Asistencia_Turno_horario1_idx` (`Turno_horario_Turno_horario` ASC, `Turno_horario_Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Asistencia_Turno_horario1`
    FOREIGN KEY (`Turno_horario_Turno_horario` , `Turno_horario_Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Turno_horario` (`Turno_horario` , `Empleado_idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Vacantes` (
  `idVacantes` INT NOT NULL,
  `Fecha_cambio` DATE NULL,
  `Tipo_cambio` VARCHAR(50) NULL,
  `Vacante` VARCHAR(50) NULL,
  `Departamento` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idVacantes`, `Empleado_idEmpleado`),
  INDEX `fk_Vacantes_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Vacantes_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Permisos_vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Permisos_vacaciones` (
  `idPermisos` INT NOT NULL,
  `Tipo_permiso` VARCHAR(20) NULL,
  `Fecha_inicio` DATE NULL,
  `Fecha_finalizacion` DATE NULL,
  `Estado` VARCHAR(10) NULL,
  `Motivo` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPermisos`, `Empleado_idEmpleado`),
  INDEX `fk_Permisos_vacaciones_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Permisos_vacaciones_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Rotacion_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Rotacion_personal` (
  `idRotacion_personal` INT NOT NULL,
  `Fecha_rotacion` DATE NULL,
  `Motivos` VARCHAR(50) NULL,
  `Tipo_rotacion` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idRotacion_personal`, `Empleado_idEmpleado`),
  INDEX `fk_Rotacion_personal_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Rotacion_personal_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Retiro_jubilacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Retiro_jubilacion` (
  `idRetiro_jubilacion` INT NOT NULL,
  `Fecha_retiro_jubilacion` DATE NULL,
  `Tipo_retiro` VARCHAR(20) NULL,
  `Motivo_retiro` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idRetiro_jubilacion`, `Empleado_idEmpleado`),
  INDEX `fk_Retiro_jubilacion_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Retiro_jubilacion_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Contacto_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Contacto_emergencia` (
  `idContacto_emergencia` INT NOT NULL,
  `Nombre_contacto` VARCHAR(50) NULL,
  `Relacion_contacto` VARCHAR(50) NULL,
  `Numero_telefono` VARCHAR(10) NULL,
  `Correo_electronico` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idContacto_emergencia`, `Empleado_idEmpleado`),
  INDEX `fk_Contacto_emergencia_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Contacto_emergencia_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Nomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Nomina` (
  `idNomina` INT NOT NULL,
  `Fecha_pago` DATE NULL,
  `Monto_bruto` VARCHAR(50) NULL,
  `Deducciones` VARCHAR(50) NULL,
  `Monto_neto` VARCHAR(50) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idNomina`, `Empleado_idEmpleado`),
  INDEX `fk_Nomina_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Nomina_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Usuario_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Usuario_has_Usuario` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_idUsuario1`),
  INDEX `fk_Usuario_has_Usuario_Usuario2_idx` (`Usuario_idUsuario1` ASC),
  INDEX `fk_Usuario_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Ashure_DR`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario2`
    FOREIGN KEY (`Usuario_idUsuario1`)
    REFERENCES `Ashure_DR`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Empleado_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Empleado_has_Usuario` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Usuario_idUsuario`),
  INDEX `fk_Empleado_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Empleado_has_Usuario_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Empleado_has_Usuario_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Ashure_DR`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Datos_salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Datos_salud` (
  `idDatos_salud` INT NOT NULL,
  `Tipo_sangre` VARCHAR(50) NULL,
  `Alergias` VARCHAR(50) NULL,
  `Enfermedades_cronicas` VARCHAR(50) NULL,
  `Historial_medico` VARCHAR(50) NULL,
  `Medico_cabecera` VARCHAR(50) NULL,
  `Telefono_medico` VARCHAR(50) NULL,
  `Ultima_revision_medica` DATE NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idDatos_salud`, `Empleado_idEmpleado`),
  INDEX `fk_Datos_salud_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Datos_salud_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Asistencia_has_Turno_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Asistencia_has_Turno_horario` (
  `Asistencia_idAsistencia` INT NOT NULL,
  `Turno_horario_Turno_horario` INT NOT NULL,
  `Turno_horario_Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`Asistencia_idAsistencia`, `Turno_horario_Turno_horario`, `Turno_horario_Empleado_idEmpleado`),
  INDEX `fk_Asistencia_has_Turno_horario_Turno_horario1_idx` (`Turno_horario_Turno_horario` ASC, `Turno_horario_Empleado_idEmpleado` ASC),
  INDEX `fk_Asistencia_has_Turno_horario_Asistencia1_idx` (`Asistencia_idAsistencia` ASC),
  CONSTRAINT `fk_Asistencia_has_Turno_horario_Asistencia1`
    FOREIGN KEY (`Asistencia_idAsistencia`)
    REFERENCES `Ashure_DR`.`Asistencia` (`idAsistencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_has_Turno_horario_Turno_horario1`
    FOREIGN KEY (`Turno_horario_Turno_horario` , `Turno_horario_Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Turno_horario` (`Turno_horario` , `Empleado_idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Empleado_has_Vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Empleado_has_Vacantes` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Vacantes_idVacantes` INT NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Vacantes_idVacantes`),
  INDEX `fk_Empleado_has_Vacantes_Vacantes1_idx` (`Vacantes_idVacantes` ASC),
  INDEX `fk_Empleado_has_Vacantes_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Empleado_has_Vacantes_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Vacantes_Vacantes1`
    FOREIGN KEY (`Vacantes_idVacantes`)
    REFERENCES `Ashure_DR`.`Vacantes` (`idVacantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Empleado_has_Permisos_vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Empleado_has_Permisos_vacaciones` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Permisos_vacaciones_idPermisos` INT NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Permisos_vacaciones_idPermisos`),
  INDEX `fk_Empleado_has_Permisos_vacaciones_Permisos_vacaciones1_idx` (`Permisos_vacaciones_idPermisos` ASC),
  INDEX `fk_Empleado_has_Permisos_vacaciones_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Empleado_has_Permisos_vacaciones_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Permisos_vacaciones_Permisos_vacaciones1`
    FOREIGN KEY (`Permisos_vacaciones_idPermisos`)
    REFERENCES `Ashure_DR`.`Permisos_vacaciones` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Rotacion_personal_has_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Rotacion_personal_has_Empleado` (
  `Rotacion_personal_idRotacion_personal` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`Rotacion_personal_idRotacion_personal`, `Empleado_idEmpleado`),
  INDEX `fk_Rotacion_personal_has_Empleado_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_Rotacion_personal_has_Empleado_Rotacion_personal1_idx` (`Rotacion_personal_idRotacion_personal` ASC),
  CONSTRAINT `fk_Rotacion_personal_has_Empleado_Rotacion_personal1`
    FOREIGN KEY (`Rotacion_personal_idRotacion_personal`)
    REFERENCES `Ashure_DR`.`Rotacion_personal` (`idRotacion_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rotacion_personal_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Contacto_emergencia_has_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Contacto_emergencia_has_Empleado` (
  `Contacto_emergencia_idContacto_emergencia` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`Contacto_emergencia_idContacto_emergencia`, `Empleado_idEmpleado`),
  INDEX `fk_Contacto_emergencia_has_Empleado_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_Contacto_emergencia_has_Empleado_Contacto_emergencia1_idx` (`Contacto_emergencia_idContacto_emergencia` ASC),
  CONSTRAINT `fk_Contacto_emergencia_has_Empleado_Contacto_emergencia1`
    FOREIGN KEY (`Contacto_emergencia_idContacto_emergencia`)
    REFERENCES `Ashure_DR`.`Contacto_emergencia` (`idContacto_emergencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacto_emergencia_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ashure_DR`.`Empleado_has_Nomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ashure_DR`.`Empleado_has_Nomina` (
  `Empleado_idEmpleado` INT NOT NULL,
  `Nomina_idNomina` INT NOT NULL,
  PRIMARY KEY (`Empleado_idEmpleado`, `Nomina_idNomina`),
  INDEX `fk_Empleado_has_Nomina_Nomina1_idx` (`Nomina_idNomina` ASC),
  INDEX `fk_Empleado_has_Nomina_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Empleado_has_Nomina_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Ashure_DR`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Nomina_Nomina1`
    FOREIGN KEY (`Nomina_idNomina`)
    REFERENCES `Ashure_DR`.`Nomina` (`idNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
